# Generated by Django 5.1 on 2024-08-28 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_blog_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
